# numpy: package for multidimensional arRAY
VECTOR(1D)

MATRIX(1D OR 2D)

### create an array

In [3]:
import numpy as np

In [1]:
list= [5,6,7]

In [4]:
np.array(list)

array([5, 6, 7])

In [6]:
y= np.array(list)
y

array([5, 6, 7])

In [7]:
list_of_lists=([1,2,3],[5,9,8],[11,12,13])

In [8]:
x=np.array(list_of_lists)
x

array([[ 1,  2,  3],
       [ 5,  9,  8],
       [11, 12, 13]])

In [10]:
np.arange(4,20)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
np.arange(4,20,5)

array([ 4,  9, 14, 19])

In [12]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [24]:
np.linspace(0,50,9)


array([ 0.  ,  6.25, 12.5 , 18.75, 25.  , 31.25, 37.5 , 43.75, 50.  ])

In [25]:
np.linspace(0,50,9,dtype=int)


array([ 0,  6, 12, 18, 25, 31, 37, 43, 50])

In [27]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [28]:
np.random.rand(1,3)

array([[0.93024241, 0.65306529, 0.63446359]])

In [30]:
np.random.randn(2,3)

array([[-0.73116653, -0.32267647,  0.25349006],
       [ 0.1158696 , -0.10521119, -1.53867317]])

In [37]:
np.random.randint(5,10,6)

array([6, 7, 7, 8, 8, 9])

In [36]:
np.random.randint(5,10.5,6)

array([7, 8, 6, 8, 5, 9])

In [38]:
np.random.randint(30,40,20)

array([30, 30, 32, 33, 32, 30, 36, 33, 30, 35, 34, 30, 34, 31, 33, 35, 31,
       33, 38, 32])

In [40]:
sample_array=np.arange(2,15,3)
sample_array

array([ 2,  5,  8, 11, 14])

In [68]:
rand_array=np.random.randint(0,20,9)
rand_array

array([17,  7, 11,  0,  5, 12,  3, 13,  4])

In [43]:
sample_array.min()

2

In [44]:
sample_array.argmin()

0

In [45]:
rand_array.max()

18

In [46]:
rand_array.argmax()

7

In [50]:
sample_array.dtype

dtype('int32')

In [51]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [52]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
b=np.random.rand(2,2,3)  # 2 list of 2x3 mat
b

array([[[0.20269119, 0.11297072, 0.15562465],
        [0.50783856, 0.56608827, 0.02321125]],

       [[0.66896316, 0.2175249 , 0.74315905],
        [0.39901139, 0.62308415, 0.3709703 ]]])

In [57]:
b.T    ## 3 list of 2x2 mat

array([[[0.20269119, 0.66896316],
        [0.50783856, 0.39901139]],

       [[0.11297072, 0.2175249 ],
        [0.56608827, 0.62308415]],

       [[0.15562465, 0.74315905],
        [0.02321125, 0.3709703 ]]])

In [69]:
rand_array.reshape(3,3)

array([[17,  7, 11],
       [ 0,  5, 12],
       [ 3, 13,  4]])

In [60]:
rand_array.reshape(3,4)

ValueError: cannot reshape array of size 9 into shape (3,4)

In [70]:
rand_array=rand_array.reshape(3,3)
rand_array

array([[17,  7, 11],
       [ 0,  5, 12],
       [ 3, 13,  4]])

In [71]:
rand_array[0]=10
rand_array

array([[10, 10, 10],
       [ 0,  5, 12],
       [ 3, 13,  4]])

In [73]:
rand_array[:]=100
rand_array

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [75]:
sample1_array=np.random.randint(30,100,20)
sample1_array

array([45, 89, 33, 31, 86, 69, 44, 63, 69, 80, 62, 88, 57, 43, 84, 78, 76,
       95, 36, 83])

In [77]:
subset=sample1_array[0:7]
subset

array([45, 89, 33, 31, 86, 69, 44])

In [80]:
z=np.array(list_of_lists)
z

array([[ 1,  2,  3],
       [ 5,  9,  8],
       [11, 12, 13]])

In [81]:
z[2][2]

13

In [82]:
z[2,2]

13

In [83]:
z[1:,0:]

array([[ 5,  9,  8],
       [11, 12, 13]])

In [84]:
np.exp(subset)

array([3.49342711e+19, 4.48961282e+38, 2.14643580e+14, 2.90488497e+13,
       2.23524660e+37, 9.25378173e+29, 1.28516001e+19])

In [85]:
np.sqrt(subset)

array([6.70820393, 9.43398113, 5.74456265, 5.56776436, 9.2736185 ,
       8.30662386, 6.63324958])

In [87]:
np.square(subset)

array([2025, 7921, 1089,  961, 7396, 4761, 1936], dtype=int32)

In [88]:
np.log(subset)

array([3.80666249, 4.48863637, 3.49650756, 3.4339872 , 4.4543473 ,
       4.2341065 , 3.78418963])

In [89]:
np.max(subset)

89

In [90]:
np.argmax(subset)

1

In [91]:
np.min(subset)

31

In [92]:
np.argmin(subset)

3

In [93]:
np.std(subset)

22.59402124276171

In [94]:
np.var(subset)

510.4897959183673

In [95]:
np.mean(subset)

56.714285714285715

In [97]:
array=np.random.rand(3,4)
array

array([[0.07585286, 0.56803946, 0.87674003, 0.78276521],
       [0.68208311, 0.5144037 , 0.41876141, 0.67130286],
       [0.78927841, 0.00380788, 0.60890673, 0.06239841]])

In [98]:
np.round(array,decimals=3)

array([[0.076, 0.568, 0.877, 0.783],
       [0.682, 0.514, 0.419, 0.671],
       [0.789, 0.004, 0.609, 0.062]])

## Pandas

In [1]:
import pandas as pd

In [2]:
labels=['a','b','c','d']

In [4]:
list=[15,20,38,42]

In [5]:
import numpy as np

In [6]:
array=np.array([1,2,3,4])

In [7]:
dict={'w':34,'m':40,'y':45,'z':50}

In [8]:
pd.Series(data=list)

0    15
1    20
2    38
3    42
dtype: int64

In [9]:
pd.Series(data=list,index=labels)

a    15
b    20
c    38
d    42
dtype: int64

In [10]:
pd.Series(labels, list)

15    a
20    b
38    c
42    d
dtype: object

In [11]:
pd.Series(dict)

w    34
m    40
y    45
z    50
dtype: int64

## pandas dataframe and indexing

In [12]:
sports1=pd.Series([10,15,20,25],index=['cricket','football','volleyball', 'basketball'])
sports1

cricket       10
football      15
volleyball    20
basketball    25
dtype: int64

In [13]:
sports1['volleyball']

20

In [14]:
sports2=pd.Series([13,25,30,45],index=['cricket','football','volleyball','golf'])
sports2

cricket       13
football      25
volleyball    30
golf          45
dtype: int64

In [15]:
sports1+sports2

basketball     NaN
cricket       23.0
football      40.0
golf           NaN
volleyball    50.0
dtype: float64

In [17]:
df1=pd.DataFrame(np.random.rand(8,5),index='a b c d e f g h'.split(),columns='s1 s2 s3 s4 s5'.split())
df1

s1        s2        s3        s4        s5
a  0.636244  0.283322  0.832733  0.231797  0.693046
b  0.283838  0.799664  0.298806  0.092272  0.597583
c  0.344535  0.579269  0.830793  0.914499  0.274287
d  0.948500  0.845478  0.082207  0.281410  0.641418
e  0.371452  0.456873  0.787336  0.339970  0.041328
f  0.959626  0.362624  0.979942  0.321664  0.985783
g  0.905211  0.836707  0.613218  0.877795  0.658728
h  0.660161  0.380711  0.715825  0.998139  0.731670

In [19]:
df1[['s1','s2','s3']]

s1        s2        s3
a  0.636244  0.283322  0.832733
b  0.283838  0.799664  0.298806
c  0.344535  0.579269  0.830793
d  0.948500  0.845478  0.082207
e  0.371452  0.456873  0.787336
f  0.959626  0.362624  0.979942
g  0.905211  0.836707  0.613218
h  0.660161  0.380711  0.715825

In [22]:
df1['s6']=df1['s1']/df1['s5']
df1

s1        s2        s3        s4        s5        s6
a  0.636244  0.283322  0.832733  0.231797  0.693046  0.918041
b  0.283838  0.799664  0.298806  0.092272  0.597583  0.474976
c  0.344535  0.579269  0.830793  0.914499  0.274287  1.256109
d  0.948500  0.845478  0.082207  0.281410  0.641418  1.478756
e  0.371452  0.456873  0.787336  0.339970  0.041328  8.987967
f  0.959626  0.362624  0.979942  0.321664  0.985783  0.973466
g  0.905211  0.836707  0.613218  0.877795  0.658728  1.374180
h  0.660161  0.380711  0.715825  0.998139  0.731670  0.902266

In [24]:
df1.drop('s5',axis=1)

s1        s2        s3        s4        s6
a  0.636244  0.283322  0.832733  0.231797  0.918041
b  0.283838  0.799664  0.298806  0.092272  0.474976
c  0.344535  0.579269  0.830793  0.914499  1.256109
d  0.948500  0.845478  0.082207  0.281410  1.478756
e  0.371452  0.456873  0.787336  0.339970  8.987967
f  0.959626  0.362624  0.979942  0.321664  0.973466
g  0.905211  0.836707  0.613218  0.877795  1.374180
h  0.660161  0.380711  0.715825  0.998139  0.902266

In [25]:
df1.drop('c')

s1        s2        s3        s4        s5        s6
a  0.636244  0.283322  0.832733  0.231797  0.693046  0.918041
b  0.283838  0.799664  0.298806  0.092272  0.597583  0.474976
d  0.948500  0.845478  0.082207  0.281410  0.641418  1.478756
e  0.371452  0.456873  0.787336  0.339970  0.041328  8.987967
f  0.959626  0.362624  0.979942  0.321664  0.985783  0.973466
g  0.905211  0.836707  0.613218  0.877795  0.658728  1.374180
h  0.660161  0.380711  0.715825  0.998139  0.731670  0.902266

In [28]:
df2={'ID':[10,12,14,16,18],'Name':['u','v','w','x','y'],'profit':[20,30,40,50,60]}
df2

{'ID': [10, 12, 14, 16, 18],
 'Name': ['u', 'v', 'w', 'x', 'y'],
 'profit': [20, 30, 40, 50, 60]}

In [30]:
df=pd.DataFrame(df2,index=[1,2,3,4,5])
df

ID Name  profit
1  10    u      20
2  12    v      30
3  14    w      40
4  16    x      50
5  18    y      60

In [33]:
##create a null vector of size 10
y=np.zeros(10,dtype=int)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
#5th value should be 1
y[4]=1
y

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [52]:
#create a vector with values ranging from 10 to 65
z=np.arange(10,66)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65])

In [53]:
#reversing of a vector
z[::-1]

array([65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [58]:
##create a 3x3 matrix with values ranging from 0 to 8
a=np.arange(0,9)
a.reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])